//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekat_Dnevnik.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DnevnikEntities : DbContext
    {
        public DnevnikEntities()
            : base("name=DnevnikEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adresa> Adresa { get; set; }
        public virtual DbSet<Email_Adresa> Email_Adresa { get; set; }
        public virtual DbSet<Kontakt> Kontakt { get; set; }
        public virtual DbSet<Ocene> Ocene { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Ucenik> Ucenik { get; set; }
        public virtual DbSet<Vrsta_Adresa> Vrsta_Adresa { get; set; }
        public virtual DbSet<Vrsta_Email> Vrsta_Email { get; set; }
        public virtual DbSet<Vrsta_Kontakta> Vrsta_Kontakta { get; set; }
    }
}
