//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekat_Dnevnik.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Ocene
    {
        [Key]
        public int IDOsoba { get; set; }
        public string Srpski { get; set; }
        public string Matematika { get; set; }
        public string Istorija { get; set; }
        public string Geografija { get; set; }
        public string Informatika { get; set; }
        public string Fizicko { get; set; }
        public string Vladanje { get; set; }
    
        public virtual Ucenik Ucenik { get; set; }
    }
}
