//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekat_Dnevnik.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Ucenik
    {
        [Key]
        public int IDOsobe { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Ime_Roditelja { get; set; }
        public string JMBG { get; set; }
        public System.DateTime Datum_Rodjenja { get; set; }
        public string Mesto_Rodjenja { get; set; }
        public string Opstina_Rodjenja { get; set; }
        public string Pol { get; set; }
        public string Broj_Licne_Karte { get; set; }
        public byte[] Fotografija { get; set; }
        public string Beleska { get; set; }
        public  int Pin { get; set; }
    
        public virtual Adresa Adresa { get; set; }
        public virtual Email_Adresa Email_Adresa { get; set; }
        public virtual Kontakt Kontakt { get; set; }
        public virtual Ocene Ocene { get; set; }
    }
}
